project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: README.qmd
      title: Readme
    - notebook: preregistration.qmd
      title: Pre-registration
  code-links:
    - text: Cleaning Script
      icon: file-code
      href: 3-Data_Analysis/10-munge.R
      target: _blank
      
filters:
  - acronyms

acronyms:
  fromfile: ./acronyms.yml
  include_unused: true
  sorting: "alphabetical-case-insensitive"
  loa_title: ''
  insert_loa: false
  insert_links: false
  
execute:
  warning: false
  message: false
  error: false
  echo: false

format:
  html:
    theme: flatly

