repos:
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.3.2
  hooks:
  - id: style-files
    args: [--style_pkg=styler, --style_fun=tidyverse_style]
  - id: roxygenize
  - id: spell-check
  - id: lintr
  - id: readme-rmd-rendered
