project:
  type: default
  output-dir: _output
  execute-dir: project

format:
  html:
    toc: true
    code-fold: true
    code-tools: true

engine: knitr

knitr:
  opts_chunk:
    echo: true
    message: false
    warning: false
